// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pnt_line
NumericVector pnt_line(const NumericVector& p0, const NumericVector& l0, const NumericVector& l1);
RcppExport SEXP _cmt_pnt_line(SEXP p0SEXP, SEXP l0SEXP, SEXP l1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type l0(l0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type l1(l1SEXP);
    rcpp_result_gen = Rcpp::wrap(pnt_line(p0, l0, l1));
    return rcpp_result_gen;
END_RCPP
}
// pnt_line_vec
NumericMatrix pnt_line_vec(const NumericMatrix& p0, const NumericVector& l0, const NumericVector& l1, const int& profile);
RcppExport SEXP _cmt_pnt_line_vec(SEXP p0SEXP, SEXP l0SEXP, SEXP l1SEXP, SEXP profileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type l0(l0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const int& >::type profile(profileSEXP);
    rcpp_result_gen = Rcpp::wrap(pnt_line_vec(p0, l0, l1, profile));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _cmt_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cmt_pnt_line", (DL_FUNC) &_cmt_pnt_line, 3},
    {"_cmt_pnt_line_vec", (DL_FUNC) &_cmt_pnt_line_vec, 4},
    {"_cmt_rcpp_hello_world", (DL_FUNC) &_cmt_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_cmt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
