# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pnt_line <- function(p0, l0, l1) {
    .Call(`_cmt_pnt_line`, p0, l0, l1)
}

pnt_line_vec <- function(p0, l0, l1, profile) {
    .Call(`_cmt_pnt_line_vec`, p0, l0, l1, profile)
}

rcpp_hello_world <- function() {
    .Call(`_cmt_rcpp_hello_world`)
}

