# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  projection of point onto line
#' 
#' This function returns projection point
#' @param p0 A numeric (length 2)  vector of the point ( long lat)  to projected onto the line defined by l0, l1 
#' @param l0 A numeric (length 2) vector of the point (long lat) defining start of projection line
#' @param l1 A numeric (length 2) vector of the point (long lat) defining end of projection line
#' @export A numwric (length 2) vector ofthe pojected position of the p0 onto line l0-l1 
pnt_line <- function(p0, l0, l1) {
    .Call(`_cmt_pnt_line`, p0, l0, l1)
}

#'  projection of points onto line
#' 
#' This function returns projection point
#' @param p0 A nuemric matrix (n*2) defining points in (long lat)  format to be projected onto line defined by l0, l1 
#' @param l0 A numeric vector
#' @param l1 A numeric vector
#' @param profiel A integer identfier for the profile
#' @export
pnt_line_vec <- function(p0, l0, l1, profile) {
    .Call(`_cmt_pnt_line_vec`, p0, l0, l1, profile)
}

rcpp_hello_world <- function() {
    .Call(`_cmt_rcpp_hello_world`)
}

